### ISSUE TITLE
实验效果和原文有出入，是我运行代码的方式不对吗？

### ISSUE THREAD

**Issue by chenyifeng654** [chenchongthu/ENSFM#1]
直接运行ENSFM代码得到的结果是不是需要一些转化才能得到论文里的结果

**Comment by chenchongthu** [comment]
直接运行就可以得到原文结果，你跑的哪一个数据集呢

**Comment by chenchongthu** [comment]
嗯知道了，之前上传的代码
parser.add_argument('--embed_size', type=int, default=8,
把embedding size改成64就可以得到我们最终的结果了，

**Comment by chenyifeng654** [comment]
谢谢
